# Arrays


In [3]:
import array as arr

In [4]:
a=arr.array('i',[1,2,3])    #creating an array a

In [5]:
a

array('i', [1, 2, 3])

In [8]:
b=arr.array('i',[4,3,2])

In [9]:
b

array('i', [4, 3, 2])

In [11]:
a[1:]           #slicing

array('i', [2, 3])

In [12]:
a[::-1]           #reversing

array('i', [3, 2, 1])

In [13]:
a.append(4)          #adding

In [14]:
a

array('i', [1, 2, 3, 4])

In [15]:
a.pop(2)             #removing

3

In [21]:
a

array('i', [1, 2, 4])

In [22]:
a.remove(1)
a

array('i', [2, 4])

In [23]:
for i in a:
    print(i,end=" ")

2 4 

In [24]:
a+b             #concatenation

array('i', [2, 4, 4, 3, 2])

# NUMPY

In [25]:
import numpy as np

In [27]:
k=np.array([(1,2,3),(2,7,6)])
m=np.array([(2,1,1),(1,4,8)])
k

array([[1, 2, 3],
       [2, 7, 6]])

In [28]:
m

array([[2, 1, 1],
       [1, 4, 8]])

In [29]:
k.ndim          #to check the dimensions

2

In [30]:
m.itemsize        #to check the size

4

In [31]:
k.dtype              #to know the datatype

dtype('int32')

In [32]:
k.size            #to know the size

6

In [33]:
m.shape            #to check the shape

(2, 3)

In [34]:
m.reshape(3,2)                  #reshape

array([[2, 1],
       [1, 1],
       [4, 8]])

In [35]:
m.min()               #to know the minimum value

1

In [36]:
m.max()               #to know the maximum number in the array

8

In [39]:
m.sum()              #to check the sum of the array

17

In [40]:
g=np.linspace(1,4,6)       #to check the numbers between the 1 and 4
g

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [42]:
m.sum(axis=0)         #columnwise

array([3, 5, 9])

In [43]:
k.sum(axis=1)           #row wise

array([ 6, 15])

In [44]:
np.sqrt(m)         #squreroot

array([[1.41421356, 1.        , 1.        ],
       [1.        , 2.        , 2.82842712]])

In [45]:
np.mean(k)          #mean

3.5

In [46]:
np.std(k)           #standard deviation

2.217355782608345

In [51]:
m

array([[2, 1, 1],
       [1, 4, 8]])

In [54]:
m[0,1]              #slicing

1

In [55]:
m[0:3,1]

array([1, 4])

In [56]:
m[1,1]

4

In [57]:
k

array([[1, 2, 3],
       [2, 7, 6]])

In [60]:
k[k>2]                  #to know the greater number then 2,1

array([3, 7, 6])

In [61]:
k[k>1]

array([2, 3, 2, 7, 6])

In [62]:
k[k!=1]              #not equal numbers

array([2, 3, 2, 7, 6])

In [63]:
k.sort()             #sorting
k

array([[1, 2, 3],
       [2, 6, 7]])

In [64]:
k+m                #arithmetic operators

array([[ 3,  3,  4],
       [ 3, 10, 15]])

In [65]:
k-m

array([[-1,  1,  2],
       [ 1,  2, -1]])

In [66]:
k%m

array([[1, 0, 0],
       [0, 2, 7]], dtype=int32)

In [67]:
k/m

array([[0.5  , 2.   , 3.   ],
       [2.   , 1.5  , 0.875]])